### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [hotnotHD/Java#1]
1. Слово `address` пишется с двумя d.
2. Классы в Джаве принято называть с большой буквы. Поля, переменные и параметры — с маленькой.
3. Название поля `vse` — плохое. Не используйте транслит в названиях.
4. Определитесь, какие классы публичные и объявите их таковыми. Придётся их поместить в файлы с соответствующими именами.
5. Класс `Triplet` - это, собственно, адрес. Лучше его так и назвать.
6. Этот самый адрес лучше возвращать из методов как есть, а не преобразовывать в строку
7. Посмотрите в документации что возвращают `Map.get`, `Map.remove` и `Map.put`. Во всех случаях проверка на `containsKey` не нужна.
8. `adds` лучше переименовать в `add`. Название метода — это обычно глагол в инфинитиве
9. Разберитесь с поведением в нестандартных ситуациях. Сейчас у вас четыре первых метода ведут себя по-разному:
 - `add` в случае наличия такого человека молча ничего не делает 
 - `delete` и `changeAddress` кидают NullPointerException
 - `getAddress`  возвращает какое-то специальное значение строки (это совсем плохо)

Подумайте ещё раз, что следует делать в таких ситуациях. Посмотрите на методы интерфейса `Map`, как на пример. Если кидаете исключение, выберите из стандартных наиболее подходящее по смыслу. Если нужно вернуть специальное значение, подумайте есть ли стандартное специальное значение, подходящее по смыслу и понятное программе. 
10. То же самое со специальными значениями в методах, возвращающих списки. Подумайте, что пойдёт не так, если вы никак не будете обрабатывать ситуацию, при которой на улице никто не живёт.
11. Метод `whoLifeRoom` какой-то странный. Во-первых, его нет в задании (а есть метод, который должен вернуть список людей, живущих в доме, которого у вас не хватает). Во-вторых, поиск людей с заданным номером комнаты — не очень осмысленная операция (может было бы логично сделать поиск людей живущих по данному адресу).
12. У класса, представляющего адрес не хватает метода `hashCode`, его принято переопределять вместе с `equals`. Также не будет лишним `equals`/`hashCode` у всей адресной книги.

**Comment by gagarski** [comment]
13. Подумайте, как поведёт себя ваша адресная книга с ключами и значениями `null`. Добавьте обработку этих ситуаций.

**Comment by gagarski** [comment]
Кажется на занятии я видел более позднюю версию, не забывайте коммитить свои изменения.

**Comment by hotnotHD** [comment]
Обновил

**Comment by gagarski** [comment]
Осталось 1 (класс с тестами), 2 (класс с тестами), 5, 6 (методы со списками людей)
